#!/bin/sh

set -e

echo "Creating db superuser ${POSTGRES_USERNAME}"
psql -q -c "DROP ROLE IF EXISTS \"$POSTGRES_USERNAME\";"
psql -q <<-EOF
    CREATE ROLE "$POSTGRES_USERNAME" WITH ENCRYPTED PASSWORD '$POSTGRES_USER_PASSWORD';
    ALTER ROLE "$POSTGRES_USERNAME" WITH ENCRYPTED PASSWORD '$POSTGRES_USER_PASSWORD';
    ALTER ROLE "$POSTGRES_USERNAME" WITH SUPERUSER;
    ALTER ROLE "$POSTGRES_USERNAME" WITH LOGIN;
EOF

echo "Creating database ${DB_NAME}"
psql -q <<-EOF
    CREATE DATABASE "$DB_NAME" WITH OWNER="$POSTGRES_USERNAME" ENCODING='UTF8';
    GRANT ALL ON DATABASE "$DB_NAME" TO "$POSTGRES_USERNAME";
EOF
